exec-once = uwsm app -- waybar &
exec-once = uwsm app -- clipse -listen
exec-once = uwsm app -- swayosd-server &
exec-once = uwsm app -- mpd & mpdris2-rs &
exec-once = uwsm app -- waypaper --restore
exec-once = uwsm app -- brightnessctl set 30%
exec-once = uwsm app -- ~/.config/hypr/scripts/xdg-desktop-portal
exec-once = uwsm app -- udiskie-mount /dev/disk/by-uuid/77C1-B789
exec-once = uwsm app -- dex -a -s ~/.config/autostart:/etc/xdg/autostart
exec-once = uwsm app -- /usr/libexec/polkit-mate-authentication-agent-1

## Assign apps to workspaces
# exec-once = [workspace 1 silent] uwsm app -- kitty
# exec-once = [workspace 2 silent] uwsm app -- nautilus
# exec-once = [workspace 3 silent] uwsm app -- cromite
# exec-once = [workspace 4 silent] uwsm app -- qbittorrent
# exec-once = [workspace 5 silent] uwsm app -- kitty -e btop

## Exec always
exec = uwsm app -- ~/.config/hypr/scripts/wp-magick
