################
### MONITORS ###
################

source = monitors.conf

#################
### AUTOSTART ###
#################

source = autostart.conf

#####################
### LOOK AND FEEL ###
#####################

source = decoration.conf

#############
### INPUT ###
#############

source = input.conf

###################
### KEYBINDINGS ###
###################

source = keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = windowrules.conf
