windowrule = suppressevent maximize, class:.*
windowrule = keepaspectratio, floating:1
windowrule = float, class:^updates|nwg-look|nwg-displays|mpv|zenity|xdg-desktop-portal-gtk|clipse|qt5ct|qt6ct|kvantummanager|nm-connection-editor|waypaper|sddm-conf|it.mijorus.gearlever|gearlever|com.github.tchx84.Flatseal|io.github.flattool.Warehouse|com-abdownloadmanager-desktop-AppKt|Hidamari|com.github.hluk.copyq|blueman-manager|localsend|localsend_app|org.localsend.localsend_app|com.github.johnfactotum.Foliate|org.gnome.Loupe|ymuse|xfce4-about|xarchiver|variety|info.febvre.Komikku|pomatez|octoxbps(.*)|octopi(.*)|qt-sudo|(.*)iwgtk(.*)|qalculate-gtk|peaclock|com.github.wwmm.easyeffects|io.gitlab.liferooter.TextPieces|audacious|launch-term|com.github.fushinari.Wordbook|(.*)megasync(.*)|MEGASync|pied|dev.mufeed.Wordbook|media-downloader|Toplevel|mangl|tvp-git-helper|pakeplus|org.nickvision.tubeconverter|Warpgui|org.kde.optiimage|app.drey.Dialect|io.gitlab.liferooter.TextPieces|blueberry.py|Wiremix|org.Waytrogen.Waytrogen|waytrogen|galculator|(.*)[Pp]ikatorrent(.*)|io.github.jeffshee.Hidamari|io.github.davidoc26.wallpaper_selector|io.github.mohfy.word2ipa|net.hypatiaproject.Hypatia|io.github.getnf.embellish|garden.jamie.Morphosis|com.network.manager|be.alexandervanhee.gradia|com.plexamp.Plexamp|com.surfshark.Surfshark|org.atheme.audacious|io.github.kolunmi.Bazaar|page.codeberg.Imaginer.Imaginer|io.frama.tractor.carburetor|com.jeffser.Pigment$
windowrule = float, title:clipse
windowrule = float, class:^Thunar$,title:^(Confirm to replace files|File Operation Progress)$
windowrule = float, class:^Thunar$,title:^Rename (.*)$
windowrule = float, class:^vlc$,title:^(Select one or more files to open)$
windowrule = float, class:python3,title:Hyprshot
windowrule = tile, class:^java-lang-Thread|install4j-org-jdownloader-update-launcher-JDLauncher|org-jdownloader-update-launcher-JDLauncher$, title:^(JDownloader 2)$
windowrule = tile, class:^net-filebot-Main|sioyek$
windowrule = float, class:^net-filebot-Main$, title:^(.*)(Popup|Format|win)(.*)$
windowrule = float, class:^anki$, title:^(Profiles)$
windowrule = float, class:^python3$, title:^(Import)$
windowrule = float, class:^Perplexity AI$, title:^[Nn]otification$
windowrule = float, class:^org.strawberrymusicplayer.strawberry$, title:^Settings — Strawberry Music Player$
windowrule = float, title:^About Mullvad Browser|Tor Browser Launcher Settings$
windowrule = float, class:^python3$, title:^Tor Browser$
windowrule = float, class:^net.ankiweb.Anki$, title:^Profiles$
windowrule = stayfocused, class:^(launch-term)$
windowrule = size 50% 50%, class:^Wiremix$
windowrule = size 60% 60%, class:^clipse$
windowrule = size 60% 60%, title:^clipse$
windowrule = size 30% 60%, class:^org.twosheds.iwgtk$

## Avoid common xwayland issues like dragging and halo around popups/menus
windowrule = noblur, xwayland:1
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

## AB-DM specific
# windowrule = noborder, class:^com-abdownloadmanager-desktop-AppKt$
# windowrule = norounding, class:^com-abdownloadmanager-desktop-AppKt$
windowrule = noshadow, class:^com-abdownloadmanager-desktop-AppKt$

## PIP specific
windowrule = float, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = keepaspectratio, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = move 73% 72%, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$ 
windowrule = size 25%, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = float, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = pin, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
