# Autostart apps
exec-once=mpd &
exec-once=dex -a
exec-once=waybar &
exec-once=mpdris2-rs &
exec-once=clipse -listen
exec-once=awww-daemon
exec-once=wallrestore
exec-once=gnome-keyring-daemon --start --components=secrets,ssh
exec-once=swayosd-server
exec-once=udisksctl mount -b /dev/disk/by-uuid/77C1-B789
