# Environment Variables
env=XDG_CURRENT_DESKTOP,mango
env=XDG_SESSION_TYPE,wayland
env=QT_QPA_PLATFORM,wayland
env=QT_QPA_PLATFORMTHEME,qt6ct
env=QT_QPA_PLATFORMTHEME_QT6,qt6ct
env=ELECTRON_OZONE_PLATFORM_HINT,auto
env=MOZ_ENABLE_WAYLAND,1
env=_JAVA_AWT_WM_NONREPARENTING,1
env=ELM_DISPLAY,wl
env=SDL_VIDEODRIVER,wayland
env=TERM,xterm-256color
env=TERMINAL,alacritty
