#!/usr/bin/env bash

# Let user draw a region with slurp
REGION=$(slurp -b 1B1F28CC -c C778DD0D -s C778DD0D -w 2)
[ -z "$REGION" ] && exit 1

# Extract coordinates and dimensions
X=$(echo $REGION | cut -d',' -f1)
Y=$(echo $REGION | cut -d',' -f2 | cut -d' ' -f1)
W=$(echo $REGION | cut -d' ' -f2 | cut -d'x' -f1)
H=$(echo $REGION | cut -d' ' -f2 | cut -d'x' -f2)

# Launch terminal with a custom class
kitty --class=launch-term &

# Wait for the "launch-term" window to appear
for i in {1..20}; do
  WINADDR=$(hyprctl clients -j | jq -r '.[] | select(.class=="launch-term") | .address')
  [ -n "$WINADDR" ] && break
  sleep 0.1
done

# If no window found, exit
[ -z "$WINADDR" ] && echo "Window not found." && exit 1

# Move and resize the window
hyprctl dispatch focuswindow address:$WINADDR
hyprctl dispatch movewindowpixel exact $X $Y,address:$WINADDR
hyprctl dispatch resizewindowpixel exact $W $H,address:$WINADDR
