### Audio and Subtitles ###

slang=en,eng
alang=ja,jp,jpn,jap,en,eng

sub-blur=0.5
sub-margin-y=60
sub-font-size=50
sub-color='#d6ffffff'
sub-shadow-offset=5.0
sub-back-color='#00000000'
sub-border-color='#266a678c'
sub-shadow-color='#00000000'
sub-font=Clear Sans Bold #Motiva

sub-scale=0.6
sub-auto=fuzzy
volume-max=150
sub-fix-timing=yes
audio-channels=auto
blend-subtitles=yes
sub-ass-override=yes
audio-file-auto=fuzzy
sub-file-paths-append=ass
sub-file-paths-append=srt
sub-file-paths-append=sub
sub-file-paths-append=subs
audio-pitch-correction=yes
audio-normalize-downmix=yes
sub-file-paths-append=subtitles
demuxer-mkv-subtitle-preroll=yes

#fs=yes
snap-window
keep-open=yes
geometry=50%:50%
autofit-larger=90%x90%
save-position-on-quit=yes
watch-later-options-remove=pause

### OSD/OSC ###

osc=yes
border=no
osd-bar=no
osd-bold=yes
osd-font-size=37
osd-font='JetBrains Mono'

### Profiles
include="~~/profiles.conf"
