# Image Path
$image = /home/kb/Pictures/Wallpapers/cozy-autumn-rain.jpg

# All Colors

$background = rgba(0f1416aa)

$blue = rgba(99ccfaaa)

$blue_container = rgba(094b72aa)

$blue_source = rgba(89b4faaa)

$blue_value = rgba(89b4faaa)

$error = rgba(ffb4abaa)

$error_container = rgba(93000aaa)

$green = rgba(91d5adaa)

$green_container = rgba(035233aa)

$green_source = rgba(a6e3a1aa)

$green_value = rgba(a6e3a1aa)

$inverse_on_surface = rgba(2c3133aa)

$inverse_primary = rgba(00687baa)

$inverse_surface = rgba(dee3e6aa)

$on_background = rgba(dee3e6aa)

$on_blue = rgba(003352aa)

$on_blue_container = rgba(cde5ffaa)

$on_error = rgba(690005aa)

$on_error_container = rgba(ffdad6aa)

$on_green = rgba(003822aa)

$on_green_container = rgba(acf2c8aa)

$on_orange = rgba(492900aa)

$on_orange_container = rgba(ffdcbdaa)

$on_primary = rgba(003641aa)

$on_primary_container = rgba(afecffaa)

$on_primary_fixed = rgba(001f27aa)

$on_primary_fixed_variant = rgba(004e5daa)

$on_purple = rgba(30285faa)

$on_purple_container = rgba(e5deffaa)

$on_red = rgba(511d3daa)

$on_red_container = rgba(ffd8eaaa)

$on_secondary = rgba(1d343aaa)

$on_secondary_container = rgba(cee7efaa)

$on_secondary_fixed = rgba(061f25aa)

$on_secondary_fixed_variant = rgba(344a51aa)

$on_surface = rgba(dee3e6aa)

$on_surface_variant = rgba(bfc8cbaa)

$on_tertiary = rgba(292e4daa)

$on_tertiary_container = rgba(dee0ffaa)

$on_tertiary_fixed = rgba(141937aa)

$on_tertiary_fixed_variant = rgba(404565aa)

$on_yellow = rgba(373100aa)

$on_yellow_container = rgba(f1e48aaa)

$orange = rgba(fcb974aa)

$orange_container = rgba(693c00aa)

$orange_source = rgba(fab387aa)

$orange_value = rgba(fab387aa)

$outline = rgba(899295aa)

$outline_variant = rgba(40484baa)

$primary = rgba(85d1e8aa)

$primary_container = rgba(004e5daa)

$primary_fixed = rgba(afecffaa)

$primary_fixed_dim = rgba(85d1e8aa)

$purple = rgba(c9bfffaa)

$purple_container = rgba(473f77aa)

$purple_source = rgba(cba6f7aa)

$purple_value = rgba(cba6f7aa)

$red = rgba(fbb0d8aa)

$red_container = rgba(6c3455aa)

$red_source = rgba(f38ba8aa)

$red_value = rgba(f38ba8aa)

$scrim = rgba(000000aa)

$secondary = rgba(b2cbd3aa)

$secondary_container = rgba(344a51aa)

$secondary_fixed = rgba(cee7efaa)

$secondary_fixed_dim = rgba(b2cbd3aa)

$shadow = rgba(000000aa)

$source_color = rgba(a7d2e0aa)

$surface = rgba(0f1416aa)

$surface_bright = rgba(343a3caa)

$surface_container = rgba(1b2022aa)

$surface_container_high = rgba(252b2daa)

$surface_container_highest = rgba(303638aa)

$surface_container_low = rgba(171c1eaa)

$surface_container_lowest = rgba(090f11aa)

$surface_dim = rgba(0f1416aa)

$surface_tint = rgba(85d1e8aa)

$surface_variant = rgba(40484baa)

$tertiary = rgba(c0c4ebaa)

$tertiary_container = rgba(404565aa)

$tertiary_fixed = rgba(dee0ffaa)

$tertiary_fixed_dim = rgba(c0c4ebaa)

$yellow = rgba(d5c871aa)

$yellow_container = rgba(4f4700aa)

$yellow_source = rgba(f9e2afaa)

$yellow_value = rgba(f9e2afaa)
