rootcolor=0x0f131cff

bordercolor=0x8990a5ff

focuscolor=0x55d6f3ff

maximizescreencolor=0x84d2e6ff

urgentcolor=0xffb4abff

scratchpadcolor=0xaec6ffff

globalcolor=0x004e5cff

overlaycolor=0x2c4678ff
