# More options see https://github.com/DreamMaoMao/mango/wiki/

# Source config modules
source=~/.config/mango/config.d/00-env.conf
source=~/.config/mango/config.d/01-effects.conf
source=~/.config/mango/config.d/02-layout.conf
source=~/.config/mango/config.d/03-keybinds.conf
source=~/.config/mango/config.d/04-rules.conf
source=~/.config/mango/config.d/05-autostart.conf

# Source the colorscheme
source=~/.config/mango/colors.conf
